### ISSUE TITLE
Creation of compiler task runner

### ISSUE THREAD

**Issue by dymurray** [konveyor/kai#324]
```[tasklist]
### Tasks
- [ ] https://github.com/konveyor/kai/issues/337
- [x] Have compiler agent attempt a fix via LLM
- [x] Compiler agent should properly determine whether the code is compilable or not and pass errors to successive agents
```

**Comment by shawn-hurley** [comment]
I believe that this fixed and closing this. 

fixed by #371 and #387 together.
