### ISSUE TITLE
Enable usage of kai binary in non-admin Windows use case

### ISSUE THREAD

**Issue by dymurray** [konveyor/kai#330]
Consider a user who is running on a secured corporate laptop.  (Think of a user in a FSI or Public Sector).

Requirements:
- Windows OS
- User is NOT able to install additional runtimes, they are limited to only using the runtimes provided in their corporate image.  We will assume this includes a JDK and an IDE
- User has limited permissions, is able to download, save, and open a compressed file (zip)
- User is NOT able to run a typical Windows installation process, i.e. not able to install libraries/files to privileged directories
- All dependencies must be contained within the zip file
- NO reliance on 3rd party utilities being present, i.e. we can not depend on a system 'grep', if we need a utility it must be bundled in the zip and must be able to run without requiring an official installation more than unzipping it.
- User is NOT able to launch a process that requires the need to open and listen on a port

```[tasklist]
### Tasks
- [ ] https://github.com/konveyor/kai/pull/321
- [ ] https://github.com/konveyor/kai/issues/336
- [ ] https://github.com/konveyor/kai/issues/335
- [x] Ensure RPC server can be run standalone without solved incident server
```

**Comment by jwmatthews** [comment]
Adding links to other things we may consider in future for bundling Python apps if we are not happy with PyInstaller:

- https://pypi.org/project/shiv/
- https://legacy.python.org/dev/peps/pep-0441/

**Comment by dymurray** [comment]
https://github.com/konveyor/kai/pull/414 to fix last piece
