### ISSUE TITLE
Automate testing of both IDE & Kai Client in a Windows environment with a non-admin user

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/kai#333]
This task is focused on capturing the work needed to automate the testing of what we believe is our most difficult end user environment, a Windows non-admin user with limited privileges running in a corporate environment.

Related to https://github.com/konveyor/kai/issues/330

The below tasks are assumed to all be executed against a Windows Desktop provisioned in AWS.
See: https://aws.amazon.com/workspaces-family/workspaces/

Further assumption, the work done to automate and test the below is expected to reside in a GitHub repository under the Konveyor organization so the community may help use/enhance this automation code.

```[tasklist]
### Tasks
- [ ] Able to launch Windows Desktop environment on AWS
- [ ] Creation of a non-admin user with limited privileges
- [ ] Able to script interaction with Windows Desktop
- [ ] Automate install of Kai client distributed as a zip file
- [ ] Automate usage of Kai client to accomplish a migration scenario (no IDE in this flow)
- [ ] Automate the evaluation of generated results via Kai Client
- [ ] Automate usage of Kai IDE Plugin to accomplish a migration scenario
- [ ] Automate the evaluation of generated results via Kai IDE Plugin
```
