### ISSUE TITLE
Implementation of Kai importer

### ISSUE THREAD

**Issue by dymurray** [konveyor/kai#369]
```[tasklist]
### Tasks
- [ ] Support authentication in the importer
- [x] Ensure functionality that importer can ingest konveyor data into kai server
- [x] Fix logging in the importer
- [ ] Fix git clone failes with branch not specified on the application.
```
