### ISSUE TITLE
Refactor Project to Support Kai RPC Client

### ISSUE THREAD

**Issue by JonahSussman** [konveyor/kai#396]
```[tasklist]
### Tasks
- [ ] Strip down back end to only serve solved incidents
- [ ] Set up repo structure to better accommodate RPC client
- [ ] Write stub RPC client
```

Some of my thoughts:

I took a previous stab at this here, but we weren't ready to have this in: https://github.com/konveyor/kai/pull/352. The big idea was the directory structure for kai looked like:

```
kai/
├─ server/      # everything related to ONLY the server
├─ rpc_client/  # everything related to ONLY the rpc client
└─ shared/      # shared things, mainly pydantic models for communication and constnants
```

**Comment by shawn-hurley** [comment]
@JonahSussman I believe that this is completed can we close?
